import React, {useEffect} from 'react';
import {Pressable, StyleSheet, Text, View} from 'react-native';
import {FlashList} from '@shopify/flash-list';
import NetInfo from '@react-native-community/netinfo';
import {Bell, ChevronRight, MoreHorizontal, Search, Settings2} from 'lucide-react-native';
import {Avatar} from '../components/Avatar';
import {Glass} from '../components/Glass';
import {SyncPill} from '../components/SyncPill';
import {conversations} from '../data/mockData';
import {useAppStore, useSyncSnapshot} from '../store/useAppStore';
import {colors, fonts, radius, spacing} from '../theme';

export function InboxScreen({navigation}: any) { const setOffline = useAppStore(state => state.setOffline); const isOffline = useAppStore(state => state.isOffline); const sync = useSyncSnapshot(); useEffect(() => { const unsubscribe = NetInfo.addEventListener(state => setOffline(!state.isConnected)); return unsubscribe; }, [setOffline]); return <View style={styles.root}><View style={styles.header}><View><Text style={styles.eyebrow}>THURSDAY · 04 SEP</Text><Text style={styles.title}>Your spaces</Text></View><View style={styles.headerActions}><Pressable style={styles.iconButton}><Search size={19} color={colors.paper} /></Pressable><Pressable style={styles.iconButton}><Bell size={19} color={colors.paper} /></Pressable></View></View><View style={styles.syncRow}><SyncPill snapshot={sync} onPress={() => navigation.navigate('SyncCenter')} />{isOffline && <Text style={styles.offline}>Offline mode</Text>}</View><View style={styles.listShell}><FlashList data={conversations} keyExtractor={item => item.id} getItemType={() => 'conversation'} contentContainerStyle={styles.listContent} renderItem={({item}) => <Pressable onPress={() => navigation.navigate('Chat', {conversationId: item.id})} style={styles.row}><Avatar label={item.avatar} color={item.avatarColor} online={item.online} /><View style={styles.rowCopy}><View style={styles.rowTop}><Text style={styles.rowTitle} numberOfLines={1}>{item.title}</Text><Text style={styles.time}>{item.lastMessageAt}</Text></View><View style={styles.rowBottom}><Text style={styles.preview} numberOfLines={1}>{item.lastMessage}</Text>{item.unreadCount > 0 && <View style={styles.unread}><Text style={styles.unreadText}>{item.unreadCount}</Text></View>}</View></View><ChevronRight size={16} color={colors.inkMuted} /></Pressable>} ListHeaderComponent={<View style={styles.sectionHeader}><Text style={styles.sectionTitle}>RECENT</Text><Pressable><Text style={styles.seeAll}>See all</Text></Pressable></View>} /></View><Glass style={styles.bottomBar}><Pressable style={styles.bottomItem}><View style={[styles.bottomIcon, styles.bottomIconActive]}><MoreHorizontal size={18} color={colors.ink} /></View><Text style={styles.bottomLabelActive}>Spaces</Text></Pressable><Pressable style={styles.bottomItem} onPress={() => navigation.navigate('SyncCenter')}><Settings2 size={20} color={colors.inkMuted} /><Text style={styles.bottomLabel}>Sync center</Text></Pressable></Glass></View>; }
const styles = StyleSheet.create({root: {flex: 1, backgroundColor: colors.ink, paddingTop: 56}, header: {paddingHorizontal: spacing.lg, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end'}, eyebrow: {fontFamily: fonts.display, color: colors.warm, fontSize: 11, letterSpacing: 2}, title: {fontFamily: fonts.display, fontSize: 34, lineHeight: 38, color: colors.paper, letterSpacing: -1.5, marginTop: 8}, headerActions: {flexDirection: 'row', gap: spacing.sm}, iconButton: {width: 40, height: 40, borderRadius: 20, backgroundColor: colors.inkRaised, justifyContent: 'center', alignItems: 'center'}, syncRow: {paddingHorizontal: spacing.lg, marginTop: spacing.lg, flexDirection: 'row', gap: spacing.sm, alignItems: 'center'}, offline: {fontFamily: fonts.body, fontSize: 12, color: colors.coral}, listShell: {flex: 1, marginTop: spacing.lg, backgroundColor: colors.paper, borderTopLeftRadius: 28, borderTopRightRadius: 28, overflow: 'hidden'}, listContent: {paddingHorizontal: spacing.lg, paddingTop: spacing.lg, paddingBottom: 120}, sectionHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.sm}, sectionTitle: {fontFamily: fonts.display, color: colors.inkMuted, fontSize: 11, letterSpacing: 1.8}, seeAll: {fontFamily: fonts.body, color: colors.ink, fontSize: 12}, row: {minHeight: 82, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.paperMuted}, rowCopy: {flex: 1, gap: 6}, rowTop: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'}, rowTitle: {fontFamily: fonts.display, color: colors.ink, fontSize: 16, maxWidth: '72%'}, time: {fontFamily: fonts.body, color: colors.inkMuted, fontSize: 11}, rowBottom: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm}, preview: {fontFamily: fonts.body, color: colors.inkMuted, fontSize: 13, flex: 1}, unread: {minWidth: 22, height: 22, paddingHorizontal: 5, borderRadius: 11, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center'}, unreadText: {fontFamily: fonts.display, color: colors.paper, fontSize: 11}, bottomBar: {position: 'absolute', bottom: 18, left: spacing.lg, right: spacing.lg, height: 68, borderRadius: 23, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around'}, bottomItem: {alignItems: 'center', gap: 4}, bottomIcon: {width: 32, height: 28, borderRadius: 13, alignItems: 'center', justifyContent: 'center'}, bottomIconActive: {backgroundColor: colors.warm}, bottomLabel: {fontFamily: fonts.body, fontSize: 10, color: colors.inkMuted}, bottomLabelActive: {fontFamily: fonts.display, fontSize: 10, color: colors.paper}});
