import React, {useEffect, useRef} from 'react';
import {Animated, ImageBackground, Pressable, StyleSheet, Text, View} from 'react-native';
import Video from 'react-native-video';
import {ArrowUpRight, LockKeyhole, Sparkles} from 'lucide-react-native';
import {useAppStore} from '../store/useAppStore';
import {colors, fonts, radius, spacing} from '../theme';

const ambientVideo = 'https://cdn.coverr.co/videos/coverr-a-woman-walking-in-a-forest-1570/1080p.mp4';
export function LoginScreen() { const signIn = useAppStore(state => state.signIn); const fade = useRef(new Animated.Value(0)).current; useEffect(() => { Animated.timing(fade, {toValue: 1, duration: 650, useNativeDriver: true}).start(); }, [fade]); return <View style={styles.root}><Video source={{uri: ambientVideo}} repeat muted resizeMode="cover" style={StyleSheet.absoluteFill} paused={false} bufferConfig={{minBufferMs: 800, maxBufferMs: 2500, bufferForPlaybackMs: 250, bufferForPlaybackAfterRebufferMs: 500}} /><ImageBackground source={require('../../assets/launch-poster.png')} resizeMode="cover" style={StyleSheet.absoluteFill} imageStyle={styles.poster} /><View style={styles.tint} /><Animated.View style={[styles.content, {opacity: fade}]}><View style={styles.brandRow}><View style={styles.brandMark}><Sparkles size={17} color={colors.ink} /></View><Text style={styles.brand}>quack</Text></View><View style={styles.hero}><Text style={styles.eyebrow}>PRIVATE BY DEFAULT</Text><Text style={styles.title}>Messages that{`\n`}keep their promise.</Text><Text style={styles.description}>A quieter way to stay close — even when your signal disappears.</Text></View><View style={styles.bottom}><View style={styles.secureRow}><LockKeyhole size={15} color={colors.paperMuted} /><Text style={styles.secure}>End-to-end encrypted · local-first</Text></View><Pressable style={styles.cta} onPress={signIn}><Text style={styles.ctaText}>Enter your space</Text><ArrowUpRight size={19} color={colors.ink} /></Pressable><Text style={styles.legal}>By continuing, you agree to the community guidelines.</Text></View></Animated.View></View>; }
const styles = StyleSheet.create({root: {flex: 1, backgroundColor: colors.ink}, poster: {opacity: 0.28}, tint: {...StyleSheet.absoluteFill, backgroundColor: 'rgba(16,18,23,0.62)'}, content: {flex: 1, paddingHorizontal: spacing.lg, paddingTop: 58, paddingBottom: 34, justifyContent: 'space-between'}, brandRow: {flexDirection: 'row', alignItems: 'center', gap: spacing.sm}, brandMark: {width: 32, height: 32, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.warm}, brand: {fontFamily: fonts.display, fontSize: 20, letterSpacing: -0.7, color: colors.white}, hero: {maxWidth: 360}, eyebrow: {fontFamily: fonts.display, color: colors.warmBright, fontSize: 12, letterSpacing: 2.5, marginBottom: spacing.md}, title: {fontFamily: fonts.display, color: colors.white, fontSize: 47, lineHeight: 49, letterSpacing: -2.2}, description: {fontFamily: fonts.body, color: colors.paperMuted, fontSize: 16, lineHeight: 24, marginTop: spacing.lg, maxWidth: 300}, bottom: {gap: spacing.md}, secureRow: {flexDirection: 'row', alignItems: 'center', gap: spacing.sm}, secure: {color: colors.paperMuted, fontFamily: fonts.body, fontSize: 12}, cta: {height: 62, paddingHorizontal: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.warm, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'}, ctaText: {fontFamily: fonts.display, color: colors.ink, fontSize: 16}, legal: {fontFamily: fonts.body, color: 'rgba(245,243,239,0.54)', textAlign: 'center', fontSize: 11}});
