import React from 'react';
import {Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {ArrowLeft, CheckCircle2, Cloud, Database, RefreshCcw, ShieldCheck, TriangleAlert} from 'lucide-react-native';
import {Glass} from '../components/Glass';
import {useSyncSnapshot} from '../store/useAppStore';
import {SyncEngine} from '../sync/SyncEngine';
import {colors, fonts, radius, spacing} from '../theme';

export function SyncCenterScreen({navigation}: any) { const snapshot = useSyncSnapshot(); return <View style={styles.root}><View style={styles.header}><Pressable onPress={() => navigation.goBack()} style={styles.back}><ArrowLeft size={20} color={colors.paper} /></Pressable><View><Text style={styles.eyebrow}>SYSTEM STATUS</Text><Text style={styles.title}>Sync center</Text></View></View><ScrollView contentContainerStyle={styles.content}><Glass style={styles.hero}><View style={styles.heroIcon}><Cloud size={23} color={colors.ink} /></View><Text style={styles.heroTitle}>{snapshot.state === 'error' ? 'A few things need you' : snapshot.state === 'running' ? 'Everything is moving' : 'You are all caught up'}</Text><Text style={styles.heroCopy}>{snapshot.state === 'error' ? 'Your messages are safe on this device. Retry when you are ready.' : 'Your local messages and the cloud are in step.'}</Text><Pressable style={styles.refresh} onPress={() => SyncEngine.run('foreground')}><RefreshCcw size={16} color={colors.ink} /><Text style={styles.refreshText}>Sync now</Text></Pressable></Glass><Text style={styles.section}>THIS DEVICE</Text><View style={styles.rows}><InfoRow icon={<Database size={18} color={colors.warm} />} label="Local queue" value={snapshot.queued ? `${snapshot.queued} waiting` : 'Empty'} /><InfoRow icon={<ShieldCheck size={18} color={colors.mint} />} label="Last successful sync" value={snapshot.lastSyncAt ? new Date(snapshot.lastSyncAt).toLocaleTimeString([], {hour: '2-digit', minute: '2-digit'}) : 'Just now'} /><InfoRow icon={<TriangleAlert size={18} color={colors.coral} />} label="Needs attention" value={snapshot.failed ? `${snapshot.failed} messages` : 'Nothing'} /></View><Text style={styles.note}>Quack writes your message to local storage before it ever touches the network. If the app closes, the queue resumes safely next time.</Text></ScrollView></View>; }
function InfoRow({icon, label, value}: {icon: React.ReactNode; label: string; value: string}) { return <View style={styles.infoRow}><View style={styles.infoIcon}>{icon}</View><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text><CheckCircle2 size={15} color={colors.mint} /></View>; }
const styles = StyleSheet.create({root: {flex: 1, backgroundColor: colors.ink, paddingTop: 54}, header: {paddingHorizontal: spacing.lg, flexDirection: 'row', alignItems: 'center', gap: spacing.md}, back: {width: 38, height: 38, borderRadius: 19, backgroundColor: colors.inkRaised, alignItems: 'center', justifyContent: 'center'}, eyebrow: {fontFamily: fonts.display, color: colors.warm, fontSize: 11, letterSpacing: 2}, title: {fontFamily: fonts.display, color: colors.paper, fontSize: 30, letterSpacing: -1, marginTop: 4}, content: {padding: spacing.lg, paddingBottom: 50}, hero: {padding: spacing.lg, alignItems: 'center', borderRadius: 28, marginBottom: spacing.xl}, heroIcon: {width: 52, height: 52, borderRadius: 26, backgroundColor: colors.warm, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.md}, heroTitle: {fontFamily: fonts.display, color: colors.paper, fontSize: 21}, heroCopy: {fontFamily: fonts.body, color: colors.inkMuted, fontSize: 14, textAlign: 'center', lineHeight: 21, marginTop: spacing.sm, maxWidth: 270}, refresh: {marginTop: spacing.lg, borderRadius: radius.pill, backgroundColor: colors.paper, paddingVertical: 11, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 7}, refreshText: {fontFamily: fonts.display, color: colors.ink, fontSize: 13}, section: {fontFamily: fonts.display, color: colors.inkMuted, letterSpacing: 1.8, fontSize: 11, marginBottom: spacing.sm}, rows: {backgroundColor: colors.inkRaised, borderRadius: radius.md, paddingHorizontal: spacing.md}, infoRow: {minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.06)'}, infoIcon: {width: 32, alignItems: 'center'}, infoLabel: {fontFamily: fonts.body, color: colors.paperMuted, fontSize: 14, flex: 1}, infoValue: {fontFamily: fonts.display, color: colors.paper, fontSize: 12}, note: {fontFamily: fonts.body, color: colors.inkMuted, fontSize: 13, lineHeight: 20, marginTop: spacing.lg, paddingHorizontal: spacing.sm}});
